// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw0yrZpEh_cOO0Jg7gHP74EVX-Tsj94jA',
    appId: '1:1079167930168:android:5c11e4e1ff7de9ce4fbbcd',
    messagingSenderId: '1079167930168',
    projectId: 'merge-quest-551a1',
    storageBucket: 'merge-quest-551a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNWpN13ZtXFH_wUv-uYaT4aPb9FJkH-E',
    appId: '1:1079167930168:ios:3f33065c8dbc9afb4fbbcd',
    messagingSenderId: '1079167930168',
    projectId: 'merge-quest-551a1',
    storageBucket: 'merge-quest-551a1.firebasestorage.app',
    androidClientId: '1079167930168-l0pu2tlbn0sc2a3asrmvmd2ht4gevf9o.apps.googleusercontent.com',
    iosClientId: '1079167930168-dclioabd6cruu29188rg9i4lpaalctsu.apps.googleusercontent.com',
    iosBundleId: 'dev.hrvojebencik.mq',
  );

}